#!/bin/bash
rm pub sub
g++ -pthread pub.cc /usr/lib/x86_64-linux-gnu/libboost_system.a /usr/lib/x86_64-linux-gnu/libboost_thread.a -o pub && g++ -pthread sub.cc /usr/lib/x86_64-linux-gnu/libboost_system.a /usr/lib/x86_64-linux-gnu/libboost_thread.a -o sub
